# Android Release build github workflow based off https://blog.logrocket.com/flutter-ci-cd-using-github-actions/
# Substito flutter-action: https://github.com/marketplace/actions/flutter-action
# Substito repository: https://github.com/subosito/flutter-action
name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "main" ] # Set to branch
  pull_request:
    branches: [ "main" ] # Set to branch

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5 - Jobs run in parallel, so the numbering here is kind of silly
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle' # speed up java setup
      # 10   
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.10.5"
          channel: 'stable'
          cache: true # speed up flutter sdk setup
      # 12
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
  # 13
  version:
      name: Create version number
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Needed to avoid commit not found GitVersion error, borrowed from https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/setup/usage-examples.md
            # Full error: GitVersion.GitVersionException: Cannot find commit 5c61deb comment. Please ensure that the repository is an unshallow clone with `git fetch --unshallow`.
        # 14
        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0.10.2
          with:
            versionSpec: "5.x"
            includePrerelease: true
        - name: Use GitVersion
          id: gitversion
          uses: gittools/actions/gitversion/execute@v0.10.2
        # 15
        - name: Create version.txt with nuGetVersion
          run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
        # 16
        - name: Upload version.txt
          uses: actions/upload-artifact@v2
          with:
            name: gitversion
            path: version.txt
            